### ISSUE TITLE
关于代码

### ISSUE THREAD

**Issue by cyq7on** [ZhihaoZhu/Auto-GUI-Code-Generation#2]
lz你好,我对"Automatic Graphics Program Generation using Attention-Based Hierarchical Decoder"非常感兴趣。该论文相关的代码能分享吗?

**Comment by lehua0817** [comment]
你好，我看了pix2code的源码和论文，也看了你的论文，该论文相关的代码能分享吗?

**Comment by ZhihaoZhu** [comment]
你好，因为我们的研究和公司有合作，所以暂时无法公开代码和数据集，望理解谢谢

lehua0817 <notifications@github.com> 于2019年4月1日周一 上午8:28写道：

**Comment by cyq7on** [comment]
好的
